stages:
  - setup
  - test
  - build
  - release

default:
  image: node:10.15.3
  cache:
    untracked: true
    paths:
      - node_modules/

setup:
  stage: setup
  script:
    - npm ci

test:
  stage: test
  script:
    - npm t

build:
  stage: build
  script:
    - npm run build
    - npm run build:docs
  artifacts:
    paths:
      - pkg
      - docs

release:
  stage: release
  before_script:
    - git config --global user.name "Scale Bot"
    - git config --global user.email "scale-bot@scaleleap.com"
    - git remote set-url origin https://gitlab-ci-token:$GIT_CI_TOKEN@gitlab.com/$CI_PROJECT_PATH.git
  script:
    - npx semantic-release
  dependencies:
    - build
  only:
    - master
